"""analytics table field renaming and users profile_pic column

Revision ID: d1d97228432c
Revises: b95170899a58
Create Date: 2024-04-28 13:50:39.669265

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1d97228432c"
down_revision: Union[str, None] = "b95170899a58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analytics",
        sa.Column("month_sales", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "analytics",
        sa.Column("month_fees", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "analytics",
        sa.Column("month_profit", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.drop_column("analytics", "net_profit")
    op.drop_column("analytics", "net_sales")
    op.drop_column("analytics", "net_fees")
    op.create_unique_constraint(
        op.f("uq_product_analytics_sku"), "product_analytics", ["sku"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_product_analytics_sku"), "product_analytics", type_="unique"
    )
    op.add_column(
        "analytics",
        sa.Column(
            "net_fees",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "analytics",
        sa.Column(
            "net_sales",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "analytics",
        sa.Column(
            "net_profit",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("analytics", "month_profit")
    op.drop_column("analytics", "month_fees")
    op.drop_column("analytics", "month_sales")
    # ### end Alembic commands ###
