"""made user id in order non nullable

Revision ID: 9cede2f5c10a
Revises: 01b6096ae949
Create Date: 2024-03-31 22:05:51.372762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cede2f5c10a'
down_revision: Union[str, None] = '01b6096ae949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'purchase_id',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'purchase_id',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("nextval('orders_purchase_id_seq'::regclass)"),
               existing_nullable=False)
    # ### end Alembic commands ###
