"""adding transaction id to orders objects

Revision ID: 61ba12ef75a9
Revises: cfa3bf7190f7
Create Date: 2024-04-01 14:26:10.817075

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61ba12ef75a9"
down_revision: Union[str, None] = "cfa3bf7190f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("sqsp_transaction_id", sa.String(), nullable=False),
    )
    op.alter_column(
        "orders",
        "external_transaction_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "external_transaction_id",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_column("orders", "sqsp_transaction_id")
    # ### end Alembic commands ###
