"""fixing our migrations

Revision ID: d4d397c3f402
Revises: 239c70580796
Create Date: 2024-04-08 15:19:20.383159

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4d397c3f402"
down_revision: Union[str, None] = "239c70580796"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_table("tracking")
    op.add_column(
        "orders",
        sa.Column("skus", postgresql.ARRAY(sa.String()), nullable=False),
    )
    op.drop_constraint("fk_orders_sku_products", "orders", type_="foreignkey")
    op.drop_column("orders", "sku")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("sku", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_orders_sku_products",
        "orders",
        "products",
        ["sku"],
        ["sku"],
    )
    op.drop_column("orders", "skus")
    op.create_table(
        "tracking",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("cursor", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "date_joined",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "date_renewed",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_member", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "emergency_contact",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "emergency_contact_phone",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    # ### end Alembic commands ###
