"""store cursor

Revision ID: 3831af77bbdd
Revises: 84058ffc1927
Create Date: 2024-04-01 15:48:12.545772

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3831af77bbdd"
down_revision: Union[str, None] = "84058ffc1927"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracking",
        sa.Column("current_cursor", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("current_cursor", name=op.f("pk_tracking")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tracking")
    # ### end Alembic commands ###
