"""adding column to users

Revision ID: 997a6f28ea27
Revises: c91d379a2583
Create Date: 2024-04-09 14:55:58.060090

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "997a6f28ea27"
down_revision: Union[str, None] = "c91d379a2583"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_joined", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("date_expired", sa.DateTime(), nullable=True))
    op.drop_column("users", "date_joined")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "date_joined",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "date_expired")
    op.drop_column("users", "first_joined")
    # ### end Alembic commands ###
