"""store cursor update

Revision ID: 239c70580796
Revises: 3831af77bbdd
Create Date: 2024-04-01 15:58:48.757030

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "239c70580796"
down_revision: Union[str, None] = "3831af77bbdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tracking", sa.Column("cursor", sa.String(), nullable=False))
    op.drop_column("tracking", "current_cursor")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracking",
        sa.Column("current_cursor", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_column("tracking", "cursor")
    # ### end Alembic commands ###
